import { icon, escapeHtml } from '../../components/ui.js';
import { renderTrendCard } from '../../components/chart.js';
import { demoBanner, pageHeading } from '../../components/student-ui.js';
export function renderGrowth(state) {
  const value=(v,max,suffix='')=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max?v+suffix:'No data';
  return `${demoBanner(state)}${pageHeading('ACTION INTO PROGRESS','My Growth','Explore your recorded history and choose one achievable next step.')}
  <div class="two-column growth-top">${renderTrendCard(state, false)}<section class="panel goal-card"><div class="section-heading"><div><p class="eyebrow">YOUR NEXT MILESTONE</p><h2>This week's goal</h2></div><span class="badge ${state.goal?.status === 'complete' ? 'positive' : 'neutral'}">${state.goal?.status === 'complete' ? 'Completed' : state.goal ? 'Planned' : 'No goal yet'}</span></div>${state.goal ? `<span class="explore-icon">${icon(state.goal.status === 'complete' ? 'task_alt' : 'flag')}</span><h3>${escapeHtml(state.goal.text)}</h3><p>A self-reported practice milestone. Completing it does not change a Success Score.</p><div class="button-row"><button class="button" data-action="toggle-goal">${icon(state.goal.status === 'complete' ? 'restart_alt' : 'check_circle')}${state.goal.status === 'complete' ? 'Reopen goal' : 'Mark complete'}</button><button class="button secondary" data-action="goal">Edit goal</button></div>` : `<div class="empty-state">${icon('flag')}<h3>Your next step starts here</h3><p>Set a weekly practice goal and keep your progress visible.</p><button class="button" data-action="goal">Set a weekly goal ${icon('add')}</button></div>`}</section></div>
  <section class="panel semester-records"><div class="section-heading"><div><h2>Semester-by-Semester Records</h2><p>Recorded measurements. Goals do not change academic records.</p></div><span class="badge neutral">Original units</span></div><div class="table-scroll"><table><thead><tr><th>Period</th><th>CGPA / 10</th><th>Attendance %</th><th>Coding assessment / 100</th></tr></thead><tbody>${state.history.length?state.history.map(r => `<tr><td><strong>${escapeHtml(r.period)}</strong></td><td>${value(r.academic,10)}</td><td>${value(r.attendance,100,'%')}</td><td>${value(r.coding,100)}</td></tr>`).join(''):'<tr><td colspan="4">No recorded history yet.</td></tr>'}</tbody></table></div></section>
`;
}
