import {renderAnalyticsSummary} from '../../components/analytics-ui.js';
import { icon,escapeHtml as e } from '../../components/ui.js';
import { renderTrendCard } from '../../components/chart.js';
import { demoBanner } from '../../components/student-ui.js';
export function renderOverview(state) {
 const s=state.student,p=state.portfolio,available=s.domains.filter(d=>d.value!==null).length;
 const education=s.program?`${e(s.program)} · Year ${s.year||'—'} · Semester ${s.semester||'—'}`:'Add your education details in Profile & Consent.';
 return `${demoBanner(state)}<section class="student-header panel"><div><p class="eyebrow">YOUR STUDENT OVERVIEW</p><h1>${e(s.name||'Welcome to your workspace')} <span class="badge neutral">${state.mode==='demo'?'DEMO-001':'Student account'}</span></h1><p>${education}</p><span class="muted">Target role: <strong>${e(s.targetRole||'Not selected')}</strong></span></div><div class="header-actions"><span class="badge positive">${icon(state.mode==='demo'?'science':'person')}${state.mode==='demo'?'Demo workspace':'Your account'}</span><button class="button" data-action="advisor">${icon('support_agent')}Advisor Connect</button></div></section>
 ${renderAnalyticsSummary(state)}<div class="hero-grid overview-hero"><section class="panel summary-card"><div class="section-heading"><div><p class="eyebrow">EVIDENCE BEFORE INSIGHTS</p><h2>Your data at a glance</h2></div><span class="badge positive">${available} sources available</span></div><div class="summary-body"><div class="source-number">${available}<span>/ ${s.domains.length}</span><small>data sources</small></div><div><h3>${state.history.length?'A clearer picture of your progress':'A fresh start, ready for your evidence'}</h3><p>${state.mode==='demo'?'Synthetic academic and career evidence is loaded from the database preview.':'Your account begins with zero skills, projects, and goals. Measurements appear when records are supplied.'}</p><progress value="${available}" max="${s.domains.length}" aria-label="Available data sources"></progress><small>${s.domains.length-available} sources have no measurement yet.</small></div></div><details class="methodology"><summary>${icon('info')}About source coverage</summary><p>Source coverage shows how many records are available; it is separate from the success score. Missing data stays unavailable.</p></details></section>${renderTrendCard(state)}</div>
 <section class="domain-section"><div class="section-heading"><div><h2>Your integrated student view</h2><p>Select a category to inspect its evidence.</p></div><span class="badge neutral">${s.domains.length-available} missing sources</span></div><div class="domain-grid">${s.domains.map(d=>`<button class="domain-card" data-domain="${e(d.id)}"><span class="domain-label">${e(d.name)}${icon(d.icon)}</span><span class="domain-value">${d.value??'—'}<small>${e(d.unit)}</small></span><span class="source-state ${d.value===null?'missing':''}">${icon(d.value===null?'info':'check_circle')}${e(d.state)}</span><span class="domain-detail">${e(d.detail)}</span><span class="domain-link">View evidence ${icon('arrow_forward')}</span></button>`).join('')}</div></section>

 <div class="two-column"><section class="panel"><p class="eyebrow">YOUR PORTFOLIO</p><h2>${p.skills.length} skills · ${p.projects.length} projects</h2><p>${p.experience.length} experience entries · ${p.achievements.length} achievements. Records you add are self-reported.</p><a class="text-button" href="#/skills">Manage your skills ${icon('arrow_forward')}</a></section><section class="panel"><p class="eyebrow">YOUR CURRENT DIRECTION</p><h2>${e(s.targetRole||'Choose a target role')}</h2><p>Career templates help you organize evidence. They do not predict hiring outcomes.</p><a class="text-button" href="#/skills">Explore target roles ${icon('arrow_forward')}</a></section></div>`;
}
