import { icon, escapeHtml } from '../../components/ui.js';
import { demoBanner, pageHeading } from '../../components/student-ui.js';
export function safeProjectUrl(value) {
  try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : null; } catch { return null; }
}
export function renderRecruiterPreview(state) {
  const p = state.portfolio;
  if (!p.consent.enabled) return `<div class="empty-state"><span class="explore-icon">${icon('visibility_off')}</span><h3>Professional profile preview is private</h3><p>Enable the preview to explore what the selected professional fields would look like.</p></div>`;
  return `<div class="recruiter-preview"><div class="preview-person"><span class="profile-initials">${escapeHtml(state.student.name.split(/\s+/).map(s => s[0]).slice(0,2).join(''))}</span><div><h3>${escapeHtml(state.student.name)}</h3><p>${escapeHtml(state.student.targetRole)}</p></div></div>${p.consent.education ? `<section><p class="eyebrow">EDUCATION</p><p>${escapeHtml(state.student.program)} · Year ${state.student.year}</p></section>` : ''}${p.consent.skills ? `<section><p class="eyebrow">SKILLS</p><div class="path-badges">${p.skills.map(s => `<span class="badge neutral">${escapeHtml(s.name)}</span>`).join('') || '<p>No skills recorded.</p>'}</div></section>` : ''}${p.consent.projects ? `<section><p class="eyebrow">PROJECTS</p>${p.projects.map(x => `<p><strong>${escapeHtml(x.title)}</strong><br>${escapeHtml(x.description)}</p>`).join('') || '<p>No projects recorded.</p>'}</section>` : ''}${!p.consent.education && !p.consent.skills && !p.consent.projects ? '<p>No optional fields selected. Only your name and target role appear in this preview.</p>' : ''}<small>Professional fields preview only. Live recruiter access is not enabled.</small></div>`;
}
export function renderProfile(state) {
  const s = state.student; const p = state.portfolio;
  return `${demoBanner(state)}${pageHeading('YOUR PROFILE, YOUR EVIDENCE','Profile & Consent','Keep professional evidence organized and explore your sharing preferences.', '<button class="button" data-action="edit-profile">'+icon('edit')+'Edit profile</button>')}
  <section class="panel profile-header"><span class="profile-initials">${escapeHtml(s.name.split(/\s+/).map(x => x[0]).slice(0,2).join(''))}</span><div><h2>${escapeHtml(s.name)}</h2><p>${escapeHtml(s.program)} · Year ${s.year} · Semester ${s.semester}</p><span class="badge neutral">${s.id} · ${state.mode==='demo'?'Demo profile':'Your profile'}</span></div><a class="button secondary" href="#/skills">Manage skills ${icon('arrow_forward')}</a></section>
  <div class="two-column profile-overview"><section class="panel"><div class="section-heading"><h2>Education & Academic Record</h2>${icon('school')}</div><dl class="definition-list"><div><dt>Program</dt><dd>${escapeHtml(s.program)}</dd></div><div><dt>Current term</dt><dd>Year ${s.year} · Semester ${s.semester}</dd></div><div><dt>CGPA / 10</dt><dd>${s.domains.find(d=>d.id==='academic').value??'No data'}</dd></div><div><dt>Attendance %</dt><dd>${s.domains.find(d=>d.id==='attendance').value??'No data'}</dd></div></dl><p class="muted">Measurements are read-only source records; missing measurements stay unavailable.</p></section><section class="panel"><div class="section-heading"><h2>Career Direction</h2>${icon('explore')}</div><h3>${escapeHtml(s.targetRole)}</h3><p>Review sample role requirements and keep evidence for the skills you want to develop.</p><div class="path-badges"><span class="badge positive">${p.skills.length} skills recorded</span><span class="badge neutral">${p.projects.length} projects</span></div><a class="text-button" href="#/skills">Change target role ${icon('arrow_forward')}</a></section></div>
  <section class="panel project-section"><div class="section-heading"><div><h2>Projects & Evidence</h2><p>Describe the work behind your skills.</p></div><button class="button secondary" data-action="add-project">${icon('add')}Add project</button></div><div class="project-grid">${p.projects.length ? p.projects.map(x => `<article class="project-item"><div class="section-heading"><span class="explore-icon">${icon('folder_open')}</span><button class="text-button" data-project="${escapeHtml(x.id)}">Edit ${icon('edit')}</button></div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description)}</p><small>${escapeHtml(x.skills)}</small>${safeProjectUrl(x.url) ? `<a class="text-button" href="${escapeHtml(safeProjectUrl(x.url))}" target="_blank" rel="noopener noreferrer">View project ${icon('open_in_new')}</a>` : ''}</article>`).join('') : '<div class="empty-state"><h3>No project evidence yet</h3><p>Add a project to explain how you applied your skills.</p></div>'}</div></section>
  <div class="two-column portfolio-extras">${[['experience','Experience','work'],['achievements','Achievements & Certifications','workspace_premium']].map(([key,label,symbol])=>`<section class="panel"><div class="section-heading"><h2>${label}</h2><button class="icon-button" data-portfolio-add="${key}" aria-label="Add ${label.toLowerCase()}">${icon('add')}</button></div>${p[key].length?p[key].map(item=>`<article class="portfolio-entry"><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description)}</p><button class="text-button" data-portfolio-edit="${key}" data-entry-id="${escapeHtml(item.id)}">Edit entry ${icon('edit')}</button></article>`).join(''):`<p>No ${label.toLowerCase()} supplied. Add a self-reported record when you have evidence.</p>`}</section>`).join('')}</div>
  <section class="consent-section"><div class="section-heading"><div><h2>Recruiter Visibility & Consent</h2><p>Choose professional fields and inspect the local preview.</p></div><span class="badge neutral">Preview only</span></div><div class="two-column"><section class="panel"><div class="privacy-heading">${icon('verified_user')}<div><h3>Preview sharing my professional profile</h3><p>Preferences are saved with your workspace. This is a visual preview; live recruiter discovery is not enabled yet.</p></div></div><label class="toggle-row"><span><strong>Enable recruiter preview</strong><small>Show the professional fields selected below.</small></span><input type="checkbox" role="switch" data-consent="enabled" ${p.consent.enabled ? 'checked' : ''}/></label><h3 class="sharing-subheading">Included in the preview</h3>${[['education','Education','Program and current year'],['skills','Skills','Skill names from your library'],['projects','Projects','Project titles and descriptions']].map(([key,label,hint]) => `<label class="toggle-row"><span><strong>${label}</strong><small>${hint}</small></span><input type="checkbox" data-consent="${key}" ${p.consent[key] ? 'checked' : ''} ${p.consent.enabled ? '' : 'disabled'}/></label>`).join('')}<div class="privacy-note">${icon('lock')}Faculty notes, internal support signals, and private contact information are never part of this preview.</div></section><section class="panel"><div class="section-heading"><h3>What Employers Would See</h3>${icon('visibility')}</div><div id="recruiter-preview">${renderRecruiterPreview(state)}</div></section></div></section>`;
}
