import { demoBanner, pageHeading } from '../../components/student-ui.js';
import { icon } from '../../components/ui.js';
import { compareScenario } from '../../app/scenario.js';
export function renderScenarioResults(state) {
  return compareScenario(state.student, state.ui.scenario).map(r => `<article class="scenario-result"><h3>${r.name}</h3><div class="scenario-numbers"><div><small>CURRENT</small><strong>${r.baseline}<span>${r.unit}</span></strong></div>${icon('arrow_forward')}<div><small>SCENARIO</small><strong>${r.scenario}<span>${r.unit}</span></strong></div></div><span class="badge ${r.delta >= 0 ? 'positive' : 'neutral'}">${r.delta > 0 ? '+' : ''}${r.delta} ${r.id === 'attendance' ? 'percentage points' : r.id === 'lms' ? 'modules' : 'assessment points'}</span></article>`).join('');
}
export function renderSimulator(state) {
  if(state.student.domains.some(d=>['attendance','placement','lms'].includes(d.id)&&d.value===null))return `${demoBanner(state)}${pageHeading('EXPLORE A POSSIBILITY','What-If Simulator','A recorded baseline is needed before comparing scenarios.')}<section class="panel empty-state"><h2>No baseline measurements yet</h2><p>Your account has no attendance, assessment, or learning-module records. We do not invent baseline scores.</p><a class="button" href="#/profile">Build your profile</a></section>`;
  state.ui.scenario ??= Object.fromEntries(['attendance','placement','lms'].map(id => [id, state.student.domains.find(d => d.id === id).value]));
  const fields = [['attendance','Overall attendance',100,'%'],['placement','Coding assessment',100,'/ 100'],['lms','Completed LMS modules',6,'of 6']];
  return `${demoBanner(state)}${pageHeading('EXPLORE A POSSIBILITY','What-If Simulator','Change a measurement and compare it with your current sample record.', '<button class="button secondary" data-action="reset-scenario">'+icon('restart_alt')+'Reset scenario</button>')}
  <div class="scenario-notice">${icon('info')}<span><strong>Hypothetical changes only.</strong> This is a measurement comparison, not a predicted Success Score. Your saved records remain unchanged.</span></div>
  <div class="simulator-grid"><section class="panel simulator-controls"><p class="eyebrow">SCENARIO PARAMETERS</p><h2>Try a different baseline</h2><p>Adjust one indicator at a time to see the numerical difference.</p>${fields.map(([id,label,max,unit]) => `<div class="slider-field"><div><label for="scenario-${id}">${label}</label><output for="scenario-${id}" id="value-${id}">${state.ui.scenario[id]} ${unit}</output></div><input type="range" id="scenario-${id}" data-scenario="${id}" min="0" max="${max}" step="1" value="${state.ui.scenario[id]}"/><div class="range-limits"><span>0</span><span>${max} ${unit}</span></div></div>`).join('')}<a class="button" href="#/growth">Turn an idea into a goal ${icon('arrow_forward')}</a></section><section class="panel"><div class="section-heading"><div><p class="eyebrow">CURRENT VS SCENARIO</p><h2>Domain-Level Comparison</h2></div><span class="badge neutral">Hypothetical</span></div><div id="scenario-results" aria-live="polite">${renderScenarioResults(state)}</div><p class="muted">A higher measurement does not guarantee academic, interview, placement, or hiring outcomes.</p></section></div>
  <section class="panel scenario-method"><h2>How this comparison works</h2><p>We copy the current sample measurements, apply your slider values, and show the difference in the same units. No profile changes are saved, and no algorithm weights are implied.</p></section>`;
}
