import {demoBanner,pageHeading} from '../../components/student-ui.js';
import {icon,escapeHtml as e} from '../../components/ui.js';
import {effortFields,defaultEffort,simulateEffort} from '../../app/scenario.js';
import {studentRecord,analyzeStudent} from '../../services/analytics.js';
const hints={study:'Supports CGPA, assignments and coding.',attendance:'Supports attendance, assignments and CGPA.',lms:'Supports assignments, CGPA and coding.',coding:'Focused improvement in coding assessment.',projects:'Practice supports coding, assignments and CGPA.',achievements:'Competition preparation supports coding and CGPA.'};
export function renderScenarioResults(state){
 const baseline=studentRecord(state),s=simulateEffort(baseline,state.ui.scenario??defaultEffort()),before=analyzeStudent(baseline,state.analyticsConfig),after=analyzeStudent(s.record,state.analyticsConfig);
 const fields=[['cgpa','CGPA',10],['attendance','Attendance',100],['lmsMarks','LMS marks',100],['coding','Coding assessment',100]];
 return `<div class="scenario-score"><span>ILLUSTRATIVE SUCCESS SCORE</span><strong>${after.score??'Unavailable'}<small>${after.score===null?'':' / 100'}</small></strong><p>Current: ${before.score??'Unavailable'} ${after.score!==null&&before.score!==null?`<span class="badge ${after.score>=before.score?'positive':'neutral'}">${after.score>=before.score?'+':''}${(after.score-before.score).toFixed(1)} points</span>`:''}</p></div><div class="table-scroll"><table class="scenario-table"><thead><tr><th>Outcome</th><th>Current</th><th>Scenario</th><th>Change</th></tr></thead><tbody>${fields.map(([key,label,max])=>{const v=s.record[key],b=baseline[key];return `<tr><td>${label}<small> / ${max}</small></td><td>${b??'No data'}</td><td><strong>${v??'No data'}</strong></td><td>${v===null?'Unavailable':(v-b>=0?'+':'')+(v-b).toFixed(2)}</td></tr>`;}).join('')}</tbody></table></div><div class="scenario-explanation"><h3>Why several values change</h3><p>Participation supports assignment learning. Assignment gains feed into CGPA and coding. Project and competition practice transfer to related skills. Gains shrink when an indicator is already near its maximum.</p><p>${s.overload?`Effort overload: ${s.overload.toFixed(1)} percentage-point penalty is applied across outcomes. Reduce some allocations to compare a more balanced plan.`:'The plan stays within the illustrative extra-effort budget. Increasing every field can trigger an overload penalty.'}</p><p><strong>Combined review:</strong> ${after.reviewIndex===null?'Rules or measurements unavailable':after.reviewIndex+'% - '+after.risk}. ${e(after.reasons.map(r=>r.text).join(' '))}</p></div>`;
}
export function renderSimulator(state){
 const baseline=studentRecord(state);
 if(!['cgpa','attendance','lmsMarks','coding'].every(key=>typeof baseline[key]==='number'))return `${demoBanner(state)}${pageHeading('EXPLORE A POSSIBILITY','What-If Simulator','Recorded measurements are needed before comparing effort scenarios.')}<section class="panel empty-state"><h2>No baseline measurements yet</h2><p>CGPA, attendance, LMS marks and coding records are required. Missing measurements are not invented.</p></section>`;
 state.ui.scenario??=defaultEffort();
 return `${demoBanner(state)}${pageHeading('EXPLORE A POSSIBILITY','What-If Simulator','Redistribute your effort and see how connected outcomes change.','<button class="button secondary" data-action="reset-scenario">'+icon('restart_alt')+'Reset scenario</button>')}<div class="scenario-notice">${icon('info')}<span><strong>Illustrative scenario.</strong> Effort changes are relative to your current routine. Results are assumptions, not predictions or saved marks.</span></div><div class="simulator-grid"><section class="panel simulator-controls"><p class="eyebrow">YOUR EFFORT PLAN</p><h2>Explore the trade-offs</h2><p>0% keeps current effort. Negative values reduce effort; positive values add it.</p>${effortFields.map(([id,label])=>`<div class="slider-field"><div><label for="scenario-${id}">${label}</label><output id="value-${id}" for="scenario-${id}">${state.ui.scenario[id]>0?'+':''}${state.ui.scenario[id]}%</output></div><input id="scenario-${id}" type="range" data-scenario="${id}" min="-100" max="100" step="5" value="${state.ui.scenario[id]}"/><small>${hints[id]}</small></div>`).join('')}</section><section class="panel simulator-outcomes"><p class="eyebrow">CONNECTED RESULTS</p><h2>Your scenario at a glance</h2><div id="scenario-results" aria-live="polite">${renderScenarioResults(state)}</div></section></div><details class="panel scenario-method"><summary>Model assumptions and score calculation</summary><p>Each positive effort change closes part of the remaining gap to the maximum with diminishing returns; reduced effort lowers the related baseline. Study, participation, assignments, projects and competition practice have explicit transfer coefficients. More than 200 total positive effort percentage points triggers a shared workload penalty. These coefficients are illustrative, not fitted to student outcomes.</p><p>The final score uses the same configured CGPA, attendance, LMS and coding weights as the overview. Projects and achievements influence assumed practice outcomes, not direct unverified achievement points. No approved policy means no score. No placement probability is calculated.</p></details>`;
}
