import { icon, escapeHtml } from '../../components/ui.js';
import { demoBanner, pageHeading } from '../../components/student-ui.js';
import { demoRoles } from '../../data/demo-student.js';
export function renderSkills(state) {
  const role = demoRoles.find(r => r.title === state.student.targetRole) ?? demoRoles[0];
  if(!role)return '<section class="panel"><h1>Role templates unavailable</h1><p>Please reload.</p></section>';
  const rows = role.requirements.map(name => ({ name, skill: state.portfolio.skills.find(s => s.name.toLowerCase() === name.toLowerCase()) }));
  const matched = rows.filter(r => r.skill?.evidence).length;
  return `${demoBanner(state)}${pageHeading('BUILD A RELEVANT PORTFOLIO','Skills & Target Role','Bring your skill claims, project evidence, and career direction together.', '<button class="button" data-action="add-skill">'+icon('add')+'Add skill</button>')}
  <section class="panel role-card"><div><p class="eyebrow">YOUR TARGET ROLE</p><h2>${state.student.targetRole?escapeHtml(role.title):'No target role selected'}</h2><p>${role.description}</p><span class="badge neutral">Sample role requirements · Not hiring criteria</span></div><div class="form-field"><label for="target-role">Explore a target role</label><select id="target-role" data-control="target-role"><option value="" ${state.student.targetRole?'':'selected'} disabled>Choose a role</option>${demoRoles.map(r => `<option ${r.title === role.title ? 'selected' : ''}>${r.title}</option>`).join('')}</select></div></section>
  <div class="two-column skills-summary"><section class="panel"><span class="explore-icon">${icon('fact_check')}</span><h3>${matched} of ${rows.length} sample requirements have evidence</h3><p>Evidence supports the comparison. A listed skill without evidence remains self-reported.</p><progress max="${rows.length}" value="${matched}" aria-label="Sample role requirements with skill evidence"></progress></section><section class="panel"><p class="eyebrow">SUGGESTED NEXT STEP</p><h3>${rows.find(r => !r.skill?.evidence)?.name ?? 'Keep strengthening your portfolio'}</h3><p>Work on a role-relevant example and record the evidence. No fit percentage is assigned.</p><button class="text-button" data-action="goal">Set a development goal ${icon('arrow_forward')}</button></section></div>
  <section class="panel"><div class="section-heading"><div><h2>Skill Comparison & Evidence</h2><p>A simple view of sample role requirements and your current records.</p></div>${icon('compare_arrows')}</div><div class="table-scroll"><table><thead><tr><th>Skill requirement</th><th>Current evidence</th><th>Proficiency claim</th><th>Next action</th></tr></thead><tbody>${rows.map(({ name, skill }) => `<tr><td><strong>${name}</strong></td><td><span class="badge ${skill?.evidence ? 'positive' : 'neutral'}">${skill?.evidence ? 'Evidence recorded' : skill ? 'Self-reported' : 'Not recorded'}</span></td><td>${skill ? escapeHtml(skill.level) : '—'}</td><td>${skill ? `<button class="text-button" data-skill="${escapeHtml(skill.id)}">View / edit ${icon('arrow_forward')}</button>` : `<button class="text-button" data-add-skill="${name}">Add skill ${icon('add')}</button>`}</td></tr>`).join('')}</tbody></table></div></section>
  <section class="panel skill-library"><div class="section-heading"><h2>My Skill Library</h2><span class="badge neutral">${state.portfolio.skills.length} recorded skills</span></div><div class="filter-bar"><div class="search-field">${icon('search')}<label class="sr-only" for="skill-search">Search your skills</label><input id="skill-search" type="search" placeholder="Search your skills…" value="${escapeHtml(state.ui.skillSearch)}"/></div><label class="sr-only" for="skill-filter">Evidence filter</label><select id="skill-filter"><option value="all" ${state.ui.skillFilter === 'all' ? 'selected' : ''}>All evidence states</option><option value="evidenced" ${state.ui.skillFilter === 'evidenced' ? 'selected' : ''}>Evidence recorded</option><option value="claimed" ${state.ui.skillFilter === 'claimed' ? 'selected' : ''}>Self-reported</option></select></div><div id="skill-results" class="skill-cards">${renderSkillResults(state)}</div></section>`;
}
export function renderSkillResults(state) {
  const skills = state.portfolio.skills.filter(s => s.name.toLowerCase().includes(state.ui.skillSearch.toLowerCase()) && (state.ui.skillFilter === 'all' || Boolean(s.evidence) === (state.ui.skillFilter === 'evidenced')));
  return skills.length ? skills.map(s => `<article class="skill-item"><div class="section-heading"><span class="explore-icon">${icon('code')}</span><span class="badge ${s.evidence ? 'positive' : 'neutral'}">${s.evidence ? 'Evidence recorded' : 'Self-reported'}</span></div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.level)} · Self-assessed</p><small>${escapeHtml(s.evidence || 'Add evidence to support this skill claim.')}</small><button class="text-button" data-skill="${escapeHtml(s.id)}">View / edit skill ${icon('arrow_forward')}</button></article>`).join('') : `<div class="empty-state"><h3>No matching skills</h3><p>Try another search or change the evidence filter.</p></div>`;
}
