import {escapeHtml as e,icon} from '../../components/ui.js';
import {demoBanner,pageHeading} from '../../components/student-ui.js';
export function filteredSubjectRecords(records,{subjectSemester='all',subjectSearch=''}={}){
 return records.filter(r=>(subjectSemester==='all'||String(r.semester)===subjectSemester)&&r.name.toLowerCase().includes(subjectSearch.toLowerCase()));
}
export function subjectSummary(records){
 const measured=records.filter(r=>typeof r.marks==='number'&&Number.isFinite(r.marks)&&r.max>0);
 const mean=measured.length?measured.reduce((sum,r)=>sum+r.marks/r.max*100,0)/measured.length:null;
 const best=measured.length?[...measured].sort((a,b)=>b.marks/b.max-a.marks/a.max)[0]:null;
 return {count:records.length,measured:measured.length,mean,best};
}
export function renderStudentSubjects(state){
 const all=state.subjectRecords??[],rows=filteredSubjectRecords(all,state.ui),summary=subjectSummary(rows);
 const terms=[...new Set(all.map(r=>r.semester))].sort((a,b)=>a-b);
 return `${demoBanner(state)}${pageHeading('TEACHING & LEARNING','Subject-Wise Academic Analytics','Inspect recorded marks, compare subjects, and see what is missing.')}
 <section class="panel"><div class="filter-bar"><div class="form-field"><label for="student-subject-semester">Semester</label><select id="student-subject-semester"><option value="all">All recorded semesters</option>${terms.map(n=>`<option value="${n}" ${state.ui.subjectSemester===String(n)?'selected':''}>Semester ${n}</option>`).join('')}</select></div><div class="form-field"><label for="student-subject-search">Subject name</label><input id="student-subject-search" type="search" value="${e(state.ui.subjectSearch??'')}" placeholder="Find a subject" maxlength="100"/></div></div></section>
 <div class="subject-summary"><article class="panel"><span class="eyebrow">RECORDED SUBJECTS</span><h2>${summary.count}</h2><p>${summary.measured} with available marks</p></article><article class="panel"><span class="eyebrow">MEAN MARKS</span><h2>${summary.mean===null?'No data':summary.mean.toFixed(1)+'%'}</h2><p>Unweighted mean of recorded percentages</p></article><article class="panel"><span class="eyebrow">HIGHEST RECORDED RESULT</span><h2>${summary.best?e(summary.best.name):'No data'}</h2><p>${summary.best?summary.best.marks+' / '+summary.best.max:'No recorded assessment to compare'}</p></article></div>
 <section class="panel spaced-panel"><div class="section-heading"><div><h2>Subject Marks & Score Breakdown</h2><p>Each subject retains its original marking scale.</p></div>${icon('bar_chart')}</div>${rows.length?rows.map(r=>`<div class="bar-row"><span>${e(r.name)} <small>Semester ${r.semester}</small></span><strong>${typeof r.marks==='number'?r.marks+' / '+r.max:'No data'}</strong>${typeof r.marks==='number'?`<progress value="${r.marks}" max="${r.max}" aria-label="${e(r.name)} recorded marks"></progress>`:''}</div>`).join(''):`<div class="empty-state"><h3>${all.length?'No matching subjects':'No subject records yet'}</h3><p>${all.length?'Change your search or semester filter.':'Your subject records will appear when the campus supplies them. New accounts have no invented marks.'}</p></div>`}</section>
 <section class="panel spaced-panel"><h2>Subject Ledger & Performance Matrix</h2><div class="table-scroll"><table><thead><tr><th>Subject</th><th>Semester</th><th>Marks</th><th>Attendance</th><th>Credits</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.name)}</td><td>${r.semester}</td><td>${typeof r.marks==='number'?r.marks+' / '+r.max:'No data'}</td><td>${typeof r.attendance==='number'?r.attendance+'%':'No data'}</td><td>${r.credits??'No data'}</td></tr>`).join('')||'<tr><td colspan="5">No subject records available.</td></tr>'}</tbody></table></div><details class="methodology"><summary>Marks, credits and GPA</summary><p>Marks percentages are descriptive measurements. GPA requires your institution’s grade conversion and credit rules; no conversion or class rank is assumed.</p></details></section>`;
}
