import {catalog} from '../../services/catalog-service.js';
import { icon,escapeHtml as e } from '../../components/ui.js';
import { pageHeading } from '../../components/student-ui.js';
import { frontendBanner,metricCards,emptyState,searchInput,initials } from '../../components/workspace-ui.js';
import { workspace,candidates,filteredCandidates,matchRequirements } from '../../services/frontend-workspaces.js';
export function candidateCards(state,items=filteredCandidates(state).slice((workspace.ui.talentPage??0)*25,((workspace.ui.talentPage??0)+1)*25)){
  return items.length?items.map(c=>{const match=matchRequirements(c);return `<article class="panel candidate-card"><div class="section-heading"><span class="profile-initials">${initials(c.name)}</span><span class="badge positive">Professional demo profile</span></div><h2>${e(c.name)}</h2><p>${e(c.program)}</p><span class="badge neutral">${e(c.targetRole)}</span><div class="path-badges">${c.skills.map(s=>`<span class="badge neutral">${e(s)}</span>`).join('')||'<span class="muted">Skills not shared</span>'}</div><p>${match.filter(x=>x.matched).length} of ${match.length} required skills recorded. This is a skill comparison, not a hiring prediction.</p><div class="button-row"><a class="button secondary" href="#/recruiter/candidate/${c.id}">View profile ${icon('arrow_forward')}</a><button class="icon-button" data-shortlist="${c.id}" aria-label="${workspace.shortlist.includes(c.id)?'Remove':'Add'} ${e(c.name)} ${workspace.shortlist.includes(c.id)?'from':'to'} shortlist" aria-pressed="${workspace.shortlist.includes(c.id)}">${icon(workspace.shortlist.includes(c.id)?'bookmark_added':'bookmark_add')}</button></div></article>`;}).join(''):emptyState('No matching candidates','Change your search or filters. Student sharing choices can also affect this local demo catalogue.');
}
export function renderRecruiterOverview(state){
  const all=candidates(state),short=all.filter(c=>workspace.shortlist.includes(c.id));
  return `${frontendBanner()}${pageHeading('CAMPUS TALENT HUB','Talent Overview','Discover professional evidence and organize your next conversation.','<a class="button" href="#/recruiter/talent">'+icon('person_search')+'Discover talent</a>')}
  ${metricCards([['Visible demo candidates',all.length,'Synthetic consent-enabled profiles','groups'],['Shortlisted',short.length,'Currently visible saved candidates','bookmark'],['Project evidence',all.filter(c=>c.projects.length).length,'Visible profiles with recorded projects','folder_open'],['Introduction drafts',workspace.requests.filter(r=>r.status==='Draft').length,'Not sent to anyone','mail']])}
  <section class="panel role-card"><div><p class="eyebrow">ACTIVE ROLE REQUIREMENTS</p><h2>${e(workspace.role.title)}</h2><p>${e(workspace.role.description)}</p><div class="path-badges">${workspace.role.required.map(s=>`<span class="badge neutral">${e(s)}</span>`).join('')}</div></div><a class="button secondary" href="#/recruiter/roles">Edit role requirements ${icon('tune')}</a></section>
  <div class="section-heading"><div><h2>Recent Sample Talent Profiles</h2><p>Only professional fields enter the comparison.</p></div><a class="text-button" href="#/recruiter/talent">View all ${icon('arrow_forward')}</a></div><div class="candidate-grid">${candidateCards(state,all.slice(0,3))}</div>
`;
}
export function renderTalent(state){
 const all=candidates(state),unique=key=>[...new Set(all.map(c=>c[key]).filter(Boolean))].sort();
 const field=(id,label,values,current)=>`<div class="form-field"><label for="${id}">${label}</label><select id="${id}"><option value="all">All ${label.toLowerCase()}</option>${values.map(value=>`<option value="${e(String(value))}" ${String(current)===String(value)?'selected':''}>${e(String(value))}</option>`).join('')}</select></div>`;
 const multi=(id,label,values,current)=>{const chosen=Array.isArray(current)?current:current&&current!=='all'?[current]:[];return `<details class="multi-filter"><summary>${label}<span>${chosen.length?chosen.map(e).join(', '):'Any'}</span></summary><div class="multi-options" role="group" aria-label="${label}">${values.map(value=>`<label><input type="checkbox" data-multi-filter="${id}" value="${e(String(value))}" ${chosen.map(String).includes(String(value))?'checked':''}/>${e(String(value))}</label>`).join('')}</div></details>`;};
 const skills=[...new Set(all.flatMap(c=>c.skills))].sort();
 const programs=[...new Set([...unique('program'),...catalog.programs])].filter(x=>x!=='Education not shared').sort();
 return `${frontendBanner()}${pageHeading('EVIDENCE-LED DISCOVERY','Candidate Discovery','Combine career, education and evidence filters to find relevant professional profiles.')}<section class="panel discovery-filters">${searchInput('talent-search','Search name, career, course or skill',workspace.ui.talentSearch)}<div class="filter-grid">${multi('talent-skill','Skills',skills,workspace.ui.talentSkill)}${field('talent-role','Target roles',catalog.roles.map(r=>r.title).concat(unique('targetRole')).filter((v,i,a)=>a.indexOf(v)===i),workspace.ui.talentRole)}${field('talent-program','Courses',programs,workspace.ui.talentProgram)}${field('talent-degree','Degrees',[...new Set([...catalog.degrees,...unique('degree')])],workspace.ui.talentDegree)}${multi('talent-year','Years',Array.from({length:10},(_,i)=>i+1),workspace.ui.talentYear)}${multi('talent-semester','Semesters',Array.from({length:20},(_,i)=>i+1),workspace.ui.talentSemester)}${field('talent-batch','Batches',unique('batch'),workspace.ui.talentBatch)}<div class="form-field"><label for="talent-evidence">Project evidence</label><select id="talent-evidence">${[['all','All evidence states'],['projects','Has recorded projects'],['none','No project supplied']].map(([v,label])=>`<option value="${v}" ${workspace.ui.talentEvidence===v?'selected':''}>${label}</option>`).join('')}</select></div><div class="form-field"><label for="talent-sort">Sort profiles</label><select id="talent-sort">${[['name','Name A–Z'],['projects','Most recorded projects'],['skills','Most matching required skills']].map(([v,label])=>`<option value="${v}" ${workspace.ui.talentSort===v?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="catalog-filter-actions"><p class="muted"><span id="talent-match-count">${filteredCandidates(state).length} of ${all.length} visible profiles match.</span> All selected skills are required. Years and semesters match any selected value. Unshared education does not match education filters.</p><button class="button secondary" data-action="reset-talent-filters">Reset filters</button></div></section><div id="talent-results" class="candidate-grid">${candidateCards(state)}</div><div class="button-row"><button class="button secondary" data-page="talent-prev" ${!workspace.ui.talentPage?'disabled':''}>Previous candidates</button><span id="talent-page-count">Page ${(workspace.ui.talentPage??0)+1} of ${Math.max(1,Math.ceil(filteredCandidates(state).length/25))}</span><button class="button secondary" data-page="talent-next" ${(workspace.ui.talentPage??0)+1>=Math.ceil(filteredCandidates(state).length/25)?'disabled':''}>Next candidates</button></div>`;
}
export function renderCandidate(state,id){
  const c=candidates(state).find(c=>c.id===id);if(!c)return `${frontendBanner()}${emptyState('Profile unavailable','This professional profile is not visible in the current local consent preview.','<a class="button" href="#/recruiter/talent">Back to discovery</a>')}`;
  const match=matchRequirements(c);
  return `${frontendBanner()}<a class="text-button" href="#/recruiter/talent">${icon('arrow_back')}Back to candidate discovery</a>${pageHeading('PROFESSIONAL CANDIDATE PROFILE',c.name,c.program,'<button class="button secondary" data-shortlist="'+c.id+'">'+icon('bookmark')+(workspace.shortlist.includes(c.id)?'Remove from shortlist':'Add to shortlist')+'</button>')}
  <section class="panel profile-header"><span class="profile-initials">${initials(c.name)}</span><div><h2>${e(c.targetRole)}</h2><p>${e(c.summary)}</p><span class="badge positive">Professional fields only</span></div><button class="button" data-request="${c.id}">${icon('mail')}Draft introduction</button></section>
  <div class="two-column role-dashboard"><section class="panel"><div class="section-heading"><h2>Role Requirement Comparison</h2><span class="badge neutral">${match.filter(x=>x.matched).length}/${match.length} recorded</span></div><p>Compared with your ${e(workspace.role.title)} requirements.</p>${match.map(m=>`<div class="requirement-row"><span>${icon(m.matched?'check_circle':'info')}${e(m.skill)}</span><span class="badge ${m.matched?'positive':'neutral'}">${m.matched?'Skill recorded':'Evidence not supplied'}</span></div>`).join('')}<p class="muted">Recorded skills are sample or self-reported evidence. Missing evidence is not proof of inability. No fit percentage or hiring outcome is calculated.</p></section><section class="panel"><h2>Skills & Professional Summary</h2><div class="path-badges">${c.skills.map(s=>`<span class="badge neutral">${e(s)}</span>`).join('')||'<p>No skills shared.</p>'}</div><p>${e(c.summary)}</p><div class="reason"><strong>${icon('verified_user')}Consent scope</strong><p>Only the professional fields enabled in this demo profile are shown. Private contact details and faculty support data are not part of this view.</p></div></section></div>
  <section class="panel"><div class="section-heading"><h2>Projects & Evidence</h2>${icon('folder_open')}</div><div class="project-grid">${c.projects.length?c.projects.map(p=>`<article class="project-item"><h3>${e(p.title)}</h3><p>${e(p.description)}</p><span class="badge neutral">Sample / self-reported evidence</span></article>`).join(''):emptyState('No project evidence shared','This profile does not include visible projects.')}</div></section><section class="panel spaced-panel"><h2>Achievements & Certifications</h2>${c.achievements.length?c.achievements.map(a=>`<p>${e(a)}</p>`).join(''):'<p>No achievements supplied in this professional profile.</p>'}</section>`;
}
export function renderRoles(){return `${frontendBanner()}${pageHeading('ROLE-RELEVANT EVIDENCE','Role & Competency Requirements','Define a simple local role and compare it with recorded professional skills.')}<section class="panel"><form id="role-form"><div class="two-column"><div><label for="role-title">Role title</label><input id="role-title" name="title" maxlength="100" value="${e(workspace.role.title)}" required/><label for="role-description">Role description</label><textarea id="role-description" name="description" maxlength="500" rows="4">${e(workspace.role.description)}</textarea><label for="role-education">Education context</label><input id="role-education" name="education" maxlength="160" value="${e(workspace.role.education)}"/></div><div><label for="role-required">Required skills</label><textarea id="role-required" name="required" rows="4" maxlength="1000" required>${e(workspace.role.required.join(', '))}</textarea><small>Comma-separated names, up to 20 skills. Matching is case-insensitive.</small><label for="role-preferred">Preferred skills</label><textarea id="role-preferred" name="preferred" rows="3" maxlength="1000">${e(workspace.role.preferred.join(', '))}</textarea><small>Preferred skills are context only; they do not produce a weighted score.</small></div></div><p class="field-error" role="alert"></p><div class="button-row"><button type="submit" class="button">Save role requirements ${icon('check')}</button><a class="button secondary" href="#/recruiter/talent">View candidates</a></div></form></section><section class="panel spaced-panel"><h2>Explainable Matching</h2><p>Each required skill is compared with the visible skill names in a professional profile. Education and preferred skills remain context for human review. We do not assign arbitrary weights or predict a hiring outcome.</p></section>`;}
export function renderShortlist(state){
  const items=candidates(state).filter(c=>workspace.shortlist.includes(c.id));
  workspace.ui.compare=workspace.ui.compare.filter(id=>items.some(c=>c.id===id));
  const selected=items.filter(c=>workspace.ui.compare.includes(c.id));
  return `${frontendBanner()}${pageHeading('ORGANIZE YOUR DISCOVERY','Shortlisted Candidates','Keep professional evidence together and compare up to three visible profiles.')}<section class="panel"><div class="section-heading"><h2>Saved Candidates</h2><span class="badge neutral">${items.length} visible</span></div>${items.length?`<div class="compare-selection">${items.map(c=>`<label class="check-filter"><input type="checkbox" data-compare="${c.id}" ${selected.some(s=>s.id===c.id)?'checked':''}/>${e(c.name)}</label>`).join('')}</div><p class="muted">Select up to three profiles for comparison. A profile becomes unavailable if its local sharing preview is disabled.</p>`:emptyState('Your shortlist is empty','Save a candidate from discovery to start a comparison.','<a class="button" href="#/recruiter/talent">Discover candidates</a>')}</section>${selected.length?`<section class="panel spaced-panel"><h2>Side-by-Side Comparison</h2><div class="table-scroll"><table><thead><tr><th>Evidence</th>${selected.map(c=>`<th>${e(c.name)}</th>`).join('')}</tr></thead><tbody><tr><td>Target role</td>${selected.map(c=>`<td>${e(c.targetRole)}</td>`).join('')}</tr><tr><td>Recorded skills</td>${selected.map(c=>`<td>${e(c.skills.join(', ')||'Not shared')}</td>`).join('')}</tr><tr><td>Required skills recorded</td>${selected.map(c=>`<td>${matchRequirements(c).filter(x=>x.matched).length} / ${workspace.role.required.length}</td>`).join('')}</tr><tr><td>Visible projects</td>${selected.map(c=>`<td>${c.projects.length}</td>`).join('')}</tr></tbody></table></div></section>`:''}<div class="candidate-grid spaced-panel">${items.length?candidateCards(state,items):''}</div>`;
}
export function renderRequests(state){
  const visible=candidates(state),items=workspace.requests.filter(r=>workspace.ui.requestFilter==='all'||r.status===workspace.ui.requestFilter);
  return `${frontendBanner()}${pageHeading('PRIVACY-AWARE CONTACT','Introduction Requests','Prepare local drafts for a future placement-mediated introduction.')}<div class="workflow-steps"><span>1 · Draft purpose</span>${icon('arrow_forward')}<span>2 · Future placement review</span>${icon('arrow_forward')}<span>3 · Consented introduction</span></div><section class="panel"><div class="filter-bar"><label for="request-filter">Draft status</label><select id="request-filter">${[['all','All drafts'],['Draft','Draft'],['Withdrawn','Withdrawn']].map(([v,label])=>`<option value="${v}" ${workspace.ui.requestFilter===v?'selected':''}>${label}</option>`).join('')}</select></div>${items.length?items.map(r=>{const c=visible.find(c=>c.id===r.candidateId);return `<article class="support-record"><div class="section-heading"><div><strong>${e(c?.name??'Profile unavailable')}</strong><small class="cell-caption">${e(r.role)}</small></div><span class="badge neutral">${r.status} · Not sent</span></div><p>${e(r.message)}</p>${r.status==='Draft'?`<button class="text-button" data-withdraw-request="${e(r.id)}">Withdraw local draft ${icon('close')}</button>`:''}</article>`;}).join(''):emptyState('No introduction drafts found','Open a professional candidate profile to prepare a local introduction draft.','<a class="button" href="#/recruiter/talent">Browse candidates</a>')}<p class="muted">Drafts are stored in this browser. No message has been sent; no private contact information is revealed.</p></section>`;
}
