import importTemplate from '../../../docs/data/student-import-example.json' with {type:'json'};
import { escapeHtml as e } from '../../components/ui.js';
export function renderManagement() {
 return `<main id="main" class="management-page" tabindex="-1"><a href="#/login" class="login-brand">Porto-Star</a><div class="page-heading"><div><p class="eyebrow">AUTHORIZED ACCOUNT DIRECTORY</p><h1>Account management</h1><p>Real registrations and synthetic preview accounts are listed separately.</p></div><button class="button secondary" id="management-exit">Sign out</button></div><section class="panel"><h2>Real accounts</h2><form id="account-search"><label for="directory-search">Search name or email</label><div class="button-row"><input id="directory-search" maxlength="100" type="search"/><button class="button">Search</button></div></form><p id="directory-status" role="status"></p><div id="directory-results"></div><div class="button-row"><button class="button secondary" id="directory-previous">Previous</button><span id="directory-page"></span><button class="button secondary" id="directory-next">Next</button></div></section><section class="panel"><h2>Campus data import</h2><p>Download the JSON structure below. This import area is reserved for authorized account managers. Live ingestion is not enabled yet.</p><button class="button secondary" id="download-data-template">Download data template</button><label for="campus-data-upload">Future student-data upload</label><input id="campus-data-upload" type="file" accept=".json" disabled/><p>Validate student identity, source records, consent and cohort assignment before enabling imports.</p></section><section class="panel"><h2>Demo score and review rules</h2><div id="demo-policy-form"></div></section><section class="panel"><h2>Synthetic ghost accounts</h2><p>Preview fillers only. These do not have passwords or real Auth identities.</p><div id="ghost-accounts"></div></section></main>`;
}
export function accountRows(rows) {
 return rows.length?`<div class="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Workspace</th><th>Email status</th><th>Registered</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.display_name||'Not supplied')}</td><td>${e(r.email)}</td><td>${e(r.role||`${r.requested_role} · pending approval`)}</td><td>${r.email_confirmed?'Confirmed':'Unconfirmed'}</td><td>${e(new Date(r.created_at).toLocaleDateString())}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state"><h3>No matching accounts</h3><p>New registrations will appear here.</p></div>';
}
export async function bindManagement(client,onExit) {
 let page=0,search='',request=0;
 const status=document.querySelector('#directory-status'),results=document.querySelector('#directory-results');
 async function load(){
  const version=++request;status.textContent='Loading accounts…';
  document.querySelector('#directory-previous').disabled=true;document.querySelector('#directory-next').disabled=true;
  const {data,error}=await client.rpc('list_campus_accounts',{search_text:search,page_number:page});
  if(version!==request||!results.isConnected)return;
  if(error){status.textContent='Could not load the directory. Confirm your authorized account and try again.';results.innerHTML='';return;}
  status.textContent=`${data.length} accounts on this page`;results.innerHTML=accountRows(data);document.querySelector('#directory-page').textContent=`Page ${page+1}`;
  document.querySelector('#directory-previous').disabled=page===0;document.querySelector('#directory-next').disabled=data.length<25;
 }
 document.querySelector('#account-search').addEventListener('submit',event=>{event.preventDefault();search=document.querySelector('#directory-search').value.trim();page=0;load();});
 document.querySelector('#directory-previous').addEventListener('click',()=>{page=Math.max(0,page-1);load();});
 document.querySelector('#directory-next').addEventListener('click',()=>{page++;load();});
 document.querySelector('#management-exit').addEventListener('click',onExit);
 await load();
 const {data,error}=await client.from('demo_workspaces').select('payload').eq('slug','aaman').single();
 const ghosts=document.querySelector('#ghost-accounts');
 document.querySelector('#download-data-template').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(importTemplate,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='student-import-example.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 if(!error){const config=data.payload.analyticsConfig,fields=['cgpa','attendance','lmsMarks','coding'];document.querySelector('#demo-policy-form').innerHTML=`<form id="demo-policy"><p>Demo only. Weights must total 100%. Review index counts checks below their thresholds.</p>${fields.map(key=>`<div class="two-column"><div><label for="weight-${key}">${e(key)} weight %</label><input id="weight-${key}" name="weight-${key}" type="number" min="0" max="100" step="0.1" value="${config.weights[key]}" required/></div><div><label for="threshold-${key}">${e(key)} review threshold</label><input id="threshold-${key}" name="threshold-${key}" type="number" min="0" max="${key==='cgpa'?10:100}" step="0.1" value="${config.thresholds[key]}" required/></div></div>`).join('')}<button class="button">Save demo rules</button><p id="policy-status" role="status"></p></form>`;document.querySelector('#demo-policy').addEventListener('submit',async event=>{event.preventDefault();const values=new FormData(event.currentTarget),weights=Object.fromEntries(fields.map(k=>[k,Number(values.get('weight-'+k))])),thresholds=Object.fromEntries(fields.map(k=>[k,Number(values.get('threshold-'+k))]));const status=document.querySelector('#policy-status');if(Math.abs(Object.values(weights).reduce((s,v)=>s+v,0)-100)>.000001){status.textContent='Weights must total 100%.';return;}const result=await client.rpc('set_demo_policy',{policy:{...config,approved:true,weights,thresholds}});status.textContent=result.error?'Could not save demo rules.':'Demo rules saved. Reload previews to see the new calculations.';});}
 if(ghosts)ghosts.innerHTML=error?'<p>Preview unavailable.</p>':`<p>${data.payload.cohort.length} synthetic students. First 25 shown.</p><ul>${data.payload.cohort.slice(0,25).map(x=>`<li>${e(x.name)} · ${e(x.id)} · Synthetic</li>`).join('')}</ul>`;
}
