import { icon,escapeHtml as e } from '../../components/ui.js';
import { pageHeading } from '../../components/student-ui.js';
import { frontendBanner,metricCards,emptyState,searchInput,initials } from '../../components/workspace-ui.js';
import { workspace,facultyStudents,filteredStudents } from '../../services/frontend-workspaces.js';
import { subjects,campusHistory } from '../../data/demo-campus.js';
import { renderTrend } from '../../components/chart.js';
const average=(rows,key)=>rows.length?(rows.reduce((n,s)=>n+s[key],0)/rows.length).toFixed(1):'—';
export function studentRows(state, rows=filteredStudents(state)) {
  return rows.length?`<div class="table-scroll"><table><thead><tr><th>Student</th><th>Cohort</th><th>CGPA / 10</th><th>Attendance</th><th>Review</th><th>Action</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${e(s.name)}</strong><small class="cell-caption">${s.id}</small></td><td>${s.cohort}</td><td>${s.cgpa}</td><td>${s.attendance}%</td><td><span class="badge ${s.review.length?'neutral':'positive'}">${s.review.length?'Review suggested':'No review prompt'}</span></td><td><a class="text-button" href="#/faculty/student/${s.id}">View student ${icon('arrow_forward')}</a></td></tr>`).join('')}</tbody></table></div>`:emptyState('No matching students','Change your search or cohort filter.');
}
function cohortFilter(){return `<label class="sr-only" for="cohort-filter">Cohort filter</label><select id="cohort-filter"><option value="all">All assigned cohorts</option>${['AI · Year 3','CSE · Year 3'].map(c=>`<option ${workspace.ui.cohort===c?'selected':''}>${c}</option>`).join('')}</select>`;}
export function renderFacultyOverview(state){
  const all=facultyStudents(state), review=all.filter(s=>s.review.length);
  return `${frontendBanner()}${pageHeading('FACULTY SUCCESS HUB','Faculty Overview','Understand your assigned sample cohorts and turn evidence into a support conversation.','<a class="button" href="#/faculty/students">'+icon('groups')+'View students</a>')}
  ${metricCards([['Assigned students',all.length,'Across two sample cohorts','groups'],['Review suggested',review.length,'Hand-curated demo prompts','support_agent'],['Mean CGPA',average(all,'cgpa'),'Arithmetic mean · / 10','school'],['Open support actions',workspace.notes.filter(n=>n.status==='Open').length,'Local faculty draft records','assignment']])}
  <div class="two-column role-dashboard"><section class="panel"><div class="section-heading"><div><p class="eyebrow">COHORT PROGRESS</p><h2>Academic Trend</h2></div><span class="badge neutral">Sample mean</span></div>${renderTrend('academic',campusHistory)}<a class="text-button" href="#/faculty/insights">Explore cohort insights ${icon('arrow_forward')}</a></section><section class="panel"><div class="section-heading"><h2>Next Support Conversations</h2>${icon('support_agent')}</div>${review.map(s=>`<article class="review-item"><div><strong>${e(s.name)}</strong><p>${e(s.review[0])}</p></div><a class="text-button" href="#/faculty/student/${s.id}">Review ${icon('arrow_forward')}</a></article>`).join('')}<p class="muted">These sample prompts assist human review; they are not diagnoses or automated risk classifications.</p></section></div>
  <section class="panel"><div class="section-heading"><h2>Assigned Student Snapshot</h2><a class="text-button" href="#/faculty/students">View all ${icon('arrow_forward')}</a></div>${studentRows(state,all)}</section>
  <div class="two-column role-links"><a class="panel explore-card" href="#/faculty/subjects"><span class="explore-icon">${icon('menu_book')}</span><h3>Subject Analytics</h3><p>Compare sample subject marks and find useful teaching conversations.</p><span class="text-button">View subjects ${icon('arrow_forward')}</span></a><a class="panel explore-card" href="#/faculty/support"><span class="explore-icon">${icon('assignment')}</span><h3>Support & Intervention Log</h3><p>Record a faculty support action and keep its follow-up visible.</p><span class="text-button">Open support log ${icon('arrow_forward')}</span></a></div>`;
}
export function renderStudents(state){return `${frontendBanner()}${pageHeading('ASSIGNED COHORTS','Students & Support Queue','Review sample records, inspect the evidence, and plan a supportive next action.')}<section class="panel"><div class="filter-bar">${searchInput('student-search','Search students',workspace.ui.studentSearch)}${cohortFilter()}<label class="check-filter"><input type="checkbox" id="review-only" ${workspace.ui.reviewOnly?'checked':''}/>Review suggested only</label></div><div id="student-results">${studentRows(state)}</div><p class="muted">Only five synthetic records are included. Production cohort authorization will be enforced at the data layer.</p></section>`;}
export function renderStudentDetail(state,id){
  const s=facultyStudents(state).find(s=>s.id===id); if(!s)return emptyState('Student not found','This student is not in the sample assigned cohort.','<a class="button" href="#/faculty/students">Back to students</a>');
  const notes=workspace.notes.filter(n=>n.studentId===id);
  return `${frontendBanner()}<a class="text-button" href="#/faculty/students">${icon('arrow_back')}Back to students</a>${pageHeading('STUDENT DRILLDOWN',s.name,`${s.id} · ${s.cohort}`,'<button class="button" data-support-student="'+s.id+'">'+icon('add')+'Record support action</button>')}
  ${metricCards([['CGPA',s.cgpa,'Sample academic record · / 10','school'],['Attendance',s.attendance+'%','Sample recorded sessions','calendar_month'],['LMS completion',s.modules+'/6','Learning modules completed','menu_book'],['Coding assessment',s.coding+'/100','Sample assessment baseline','code']])}
  <section class="panel source-coverage"><div class="section-heading"><h2>Unified Source Coverage</h2><span class="badge neutral">5 of 7 categories supplied</span></div><div class="path-badges">${['Academic','Attendance','LMS','Placement','Skills'].map(name=>`<span class="badge positive">${name} · Sample record</span>`).join('')}<span class="badge neutral">Engagement · Not supplied</span><span class="badge neutral">Feedback · Not supplied</span></div><p class="muted">Missing sources are unavailable, not zero. This faculty fixture has fewer source categories than the student overview; no score is derived from this partial record.</p></section>
  <div class="two-column role-dashboard"><section class="panel"><h2>Evidence & Review Context</h2>${s.review.length?s.review.map(reason=>`<div class="reason review-reason"><strong>${icon('info')}Review suggested</strong><p>${e(reason)}</p></div>`).join(''):'<div class="reason"><strong>No sample review prompt</strong><p>Continue regular faculty check-ins. This does not imply certainty about future outcomes.</p></div>'}<details class="methodology"><summary>How to interpret this record</summary><p>Review prompts were curated for this frontend demonstration. A Success Score and risk model are awaiting agreed indicators and thresholds. No automated diagnosis or action has been applied.</p></details></section><section class="panel"><h2>Skills & Subject Evidence</h2><div class="path-badges">${s.skills.map(skill=>`<span class="badge neutral">${e(skill)}</span>`).join('')}</div>${subjects.map((name,i)=>`<div class="bar-row"><span>${name}</span><strong>${s.subjects[i]}/100</strong><progress value="${s.subjects[i]}" max="100" aria-label="${name} marks"></progress></div>`).join('')}<p class="muted">Skill claims and marks are synthetic, without institutional verification.</p></section></div>
  <section class="panel"><div class="section-heading"><h2>Faculty Support History</h2><span class="badge neutral">Faculty workspace only</span></div>${supportRows(state,notes)}</section>`;
}
export function renderInsights(state){
  const rows=facultyStudents(state).filter(s=>workspace.ui.cohort==='all'||s.cohort===workspace.ui.cohort);
  const gaps=['Git','SQL','Python','Communication'].map(skill=>({skill,count:rows.filter(s=>!s.skills.includes(skill)).length}));
  return `${frontendBanner()}${pageHeading('COHORT INTELLIGENCE','Class & Department Insights','Use descriptive sample data to decide what to review next.')}<div class="filter-bar">${cohortFilter()}</div>${metricCards([['Students',rows.length,'In the selected sample cohort','groups'],['Mean CGPA',average(rows,'cgpa'),'Arithmetic mean · / 10','school'],['Mean attendance',average(rows,'attendance')+'%','Arithmetic mean of sample percentages','calendar_month'],['Review prompts',rows.filter(s=>s.review.length).length,'Students with a curated review prompt','support_agent']])}
  <div class="two-column role-dashboard"><section class="panel"><h2>Skills Not Recorded</h2><p>Absence of a skill record is not proof that a student lacks the skill.</p>${gaps.map(g=>`<div class="bar-row"><span>${g.skill}</span><strong>${g.count} of ${rows.length}</strong><progress max="${rows.length||1}" value="${g.count}" aria-label="Students without ${g.skill} recorded"></progress></div>`).join('')}</section><section class="panel"><h2>Support Opportunities</h2><p>Start with evidence and a conversation rather than an irreversible label.</p><div class="reason"><strong>Learning-module completion</strong><p>${rows.filter(s=>s.modules<6).length} of ${rows.length} students have unfinished sample modules. Use the student view to inspect context.</p></div><div class="button-row"><a class="button" href="#/faculty/students">Review students ${icon('arrow_forward')}</a></div><details class="methodology"><summary>Summary methodology</summary><p>Means use all selected synthetic records equally. Skill counts compare exact recorded names. Review counts use fixture prompts, not predictive thresholds.</p></details></section></div>`;
}
export function renderSubjects(state){
  const rows=facultyStudents(state),index=workspace.ui.subject;
  const mean=(rows.reduce((n,s)=>n+s.subjects[index],0)/rows.length).toFixed(1);
  return `${frontendBanner()}${pageHeading('TEACHING & LEARNING','Subject-Wise Academic Analytics','Compare sample marks and identify evidence to discuss with students.')}<section class="panel"><div class="filter-bar"><label for="subject-filter">Selected subject</label><select id="subject-filter">${subjects.map((name,i)=>`<option value="${i}" ${i===index?'selected':''}>${name}</option>`).join('')}</select></div><div class="two-column"><div><p class="eyebrow">SAMPLE SUBJECT MEAN</p><h2>${subjects[index]}</h2><div class="large-measure">${mean}<small>/ 100 marks</small></div><p>Arithmetic mean of five synthetic marks, without a grade or risk band.</p></div><div>${rows.map(s=>`<div class="bar-row"><span>${e(s.name)}</span><strong>${s.subjects[index]}/100</strong><progress value="${s.subjects[index]}" max="100" aria-label="${e(s.name)} sample marks"></progress></div>`).join('')}</div></div></section><section class="panel spaced-panel"><h2>Subject Ledger</h2><div class="table-scroll"><table><thead><tr><th>Student</th>${subjects.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(s=>`<tr><td><a href="#/faculty/student/${s.id}">${e(s.name)}</a></td>${s.subjects.map(mark=>`<td>${mark}/100</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;
}
export function supportRows(state,notes=workspace.notes){
  const all=facultyStudents(state);
  return notes.length?`<div class="support-list">${notes.map(n=>`<article class="support-record"><div class="section-heading"><div><strong>${e(all.find(s=>s.id===n.studentId)?.name??'Sample student')}</strong><small class="cell-caption">${e(n.category)} · Follow-up ${e(n.followUp||'not set')}</small></div><span class="badge ${n.status==='Complete'?'positive':'neutral'}">${n.status}</span></div><p>${e(n.note)}</p><button class="text-button" data-support-toggle="${e(n.id)}">${n.status==='Open'?'Mark complete':'Reopen action'} ${icon('check_circle')}</button></article>`).join('')}</div>`:emptyState('No support actions recorded','Record a supportive action and a follow-up date. Notes stay in the local faculty preview.');
}
export function renderSupport(state){
  const notes=workspace.notes.filter(n=>workspace.ui.supportFilter==='all'||n.status===workspace.ui.supportFilter);
  return `${frontendBanner()}${pageHeading('FACULTY FOLLOW-UP','Support & Intervention Log','Keep the action, context, and next follow-up together.','<button class="button" data-action="record-support">'+icon('add')+'Log support action</button>')}<div class="scenario-notice">${icon('lock')}<span>Faculty-only in the product model. This frontend contains synthetic notes and has no authentication; do not enter real sensitive student information.</span></div><section class="panel"><div class="filter-bar"><label for="support-filter">Action status</label><select id="support-filter">${[['all','All actions'],['Open','Open'],['Complete','Complete']].map(([v,label])=>`<option value="${v}" ${workspace.ui.supportFilter===v?'selected':''}>${label}</option>`).join('')}</select></div>${supportRows(state,notes)}</section>`;
}
