import fs from 'node:fs';
const path=new URL('../supabase/seeds/demo-workspace.json',import.meta.url),p=JSON.parse(fs.readFileSync(path));
// Reproducible Box-Muller normal samples, not real students or outcome data.
let seed=20261008;const uniform=()=>{seed=(1664525*seed+1013904223)>>>0;return(seed+.5)/4294967296;};
const normal=()=>Math.sqrt(-2*Math.log(uniform()))*Math.cos(2*Math.PI*uniform());
const sample=(mean,sd,min,max,digits=0)=>Number(Math.min(max,Math.max(min,mean+sd*normal())).toFixed(digits));
const courses=[['B.Tech','Artificial Intelligence',['Data Structures','Database Systems','AI & Machine Learning'],'AI Engineer',['Python','SQL','Machine Learning']],['B.Tech','Computer Science',['Data Structures','Database Systems','Cloud Computing'],'Software Developer',['JavaScript','Git','SQL']],['B.Tech','Mechanical Engineering',['Engineering Mechanics','Thermodynamics','Engineering Mathematics'],'Mechanical Engineer',['CAD','Thermodynamics']],['B.Com','Commerce',['Financial Accounting','Business Economics','Business Communication'],'Accountant',['Accounting','Excel']],['B.Sc','Biotechnology',['Biochemistry','Microbiology','Research Methods'],'Biotechnology Researcher',['Laboratory Methods','Research']],['B.A.','Journalism',['Literature','History','Research Methods'],'Journalist',['Writing','Interviewing']],['BBA','Business Administration',['Marketing Management','Organizational Behaviour','Business Economics'],'Business Analyst',['Excel','Communication']],['B.Sc Nursing','Nursing',['Human Anatomy','Clinical Practice','Pharmacology'],'Nursing Professional',['Patient Care','Clinical Practice']]];
p.cohort=p.cohort.slice(0,5);
for(const s of p.cohort){s.synthetic=true;s.lmsMarks=sample(70,15,0,100);s.lmsMax=100;s.assignmentCompletion=s.modules/6*100;s.backlogs=0;s.subjectMarks=Object.fromEntries(p.subjects.map((x,i)=>[x,s.subjects[i]]));s.engagement={events:2,hackathons:1,certifications:0};s.placement={coding:s.coding,aptitude:sample(65,18,0,100),mockInterview:sample(65,15,0,100)};s.feedback=null;s.program=s.cohort.startsWith('AI')?'Artificial Intelligence':'Computer Science';}
for(let i=6;i<=500;i++){
 const [degree,program,names,role,skills]=courses[(i-6)%courses.length],ability=normal();
 const cgpa=sample(7.2+ability*.6,.65,0,10,2),attendance=sample(82+ability*4,9,0,100),coding=sample(63+ability*9,14,0,100),lmsMarks=sample(70+ability*7,15,0,100),year=1+(Math.floor((i-6)/courses.length)%4),semester=year*2-1;
 const subjectMarks=Object.fromEntries(names.map(name=>[name,sample(cgpa*10,8,0,100)]));
 p.cohort.push({id:`DEMO-${String(i).padStart(3,'0')}`,name:`Demo Student ${String(i).padStart(3,'0')}`,synthetic:true,cohort:`${program} · Year ${year}`,degree,program,year,semester,batch:`${2026-year+1}–${2030-year+1}`,cgpa,attendance,coding,lmsMarks,lmsMax:100,modules:sample(4,1.5,0,6),assignmentCompletion:sample(78,18,0,100),backlogs:sample(cgpa<6?2:0,.7,0,5),skills:skills.slice(0,sample(2,1,0,skills.length)),review:[],subjects:p.subjects.map(name=>subjectMarks[name]??null),subjectMarks,engagement:{events:sample(3,2,0,12),hackathons:sample(1,1,0,5),certifications:sample(2,1.5,0,8)},placement:{coding,aptitude:sample(65+ability*5,16,0,100),mockInterview:sample(62+ability*5,16,0,100)},feedback:i%13===0?null:sample(3.6,.65,1,5,1),targetRole:role});
}
p.professionalCandidates=p.professionalCandidates.slice(0,3);
for(const s of p.cohort.slice(5)){if(Number(s.id.slice(5))%4===0)continue;p.professionalCandidates.push({id:`talent-${s.id.toLowerCase()}`,name:s.name,program:s.program,degree:s.degree,year:s.year,semester:s.semester,batch:s.batch,targetRole:s.targetRole,skills:s.skills,projects:Number(s.id.slice(5))%3===0?[]:[{title:'Synthetic course project',description:'Generated professional evidence for testing only; not faculty verified.'}],achievements:[],summary:'Synthetic consent-enabled professional profile. Not a real candidate.'});}
p.analyticsConfig={version:'demo-v1',approved:true,label:'Illustrative demo rubric',weights:{cgpa:25,attendance:25,lmsMarks:25,coding:25},thresholds:{cgpa:6,attendance:75,lmsMarks:50,coding:50},strongAcademic:8};
p.generation={seed:20261008,count:500,method:'Box-Muller normal draws, clamped to legal ranges, rounded; shared ability factor for correlated academic/assessment data',note:'First five existing hand-curated demo records retained. 495 generated students. This distribution is synthetic, not a fitted campus model.',means:{cgpa:7.2,attendance:82,lmsMarks:70,coding:63},standardDeviations:{cgpa:.65,attendance:9,lmsMarks:15,coding:14}};
fs.writeFileSync(path,JSON.stringify(p,null,2)+'\n');
fs.mkdirSync(new URL('../docs/data/',import.meta.url),{recursive:true});
fs.writeFileSync(new URL('../docs/data/student-import-example.json',import.meta.url),JSON.stringify({schemaVersion:1,synthetic:true,students:p.cohort.slice(0,2)},null,2)+'\n');
console.log(JSON.stringify({students:p.cohort.length,professionalProfiles:p.professionalCandidates.length,seed:p.generation.seed}));
